<div class="header">
 <!--  <a href="#default" class="logo">CompanyLogo</a> -->
  <div class="header-right">
    <a class="active" href="#myaccount">My Account</a>
    <a href="#wishlist">Wish List</a>
    <a href="#shoppingcart">Shopping Cart</a>
    <a href="#checkout">Checkout</a>
  </div>
</div>






<style>
	
	/* Style the header with a grey background and some padding */
.header {
  overflow: hidden;
  background-color: black;
  padding: 5px 0 8px 0;
}

/* Style the header links */
.header a {
  float: left;
  color: grey;
  text-align: center;
  padding: 12px;
  text-decoration: none; 
  line-height: 25px;
  border-radius: 4px;
}

/* Style the logo link (notice that we set the same value of line-height and font-size to prevent the header to increase when the font gets bigger */
/*.header a.logo {
  font-size: 25px;
  font-weight: bold;
}*/

/* Change the background color on mouse-over */
.header a:hover {
 /* background-color: #ddd;*/
  color: white;
}

/* Style the active/current link*/


/* Float the link section to the right */
.header-right {
  float: right;
}

/* Add media queries for responsiveness - when the screen is 500px wide or less, stack the links on top of each other */ 
@media screen and (max-width: 640px) {
  .header a {
    float: none;
    display: block;
    text-align: left;
  }
  .header-right {
    float: none;
  }
}

</style>

